// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMV2NUKixOK0tNPhYAF8wU4PGd3mfcKE',
    appId: '1:724369051483:web:8e14be64839712e5e0d47e',
    messagingSenderId: '724369051483',
    projectId: 'vocabulary-28d9e',
    authDomain: 'vocabulary-28d9e.firebaseapp.com',
    storageBucket: 'vocabulary-28d9e.appspot.com',
    measurementId: 'G-GS7XC95VKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPoN-ndwI2cXjdgptlI3RHH8TeGtT564c',
    appId: '1:724369051483:android:1627065573ce6b7be0d47e',
    messagingSenderId: '724369051483',
    projectId: 'vocabulary-28d9e',
    storageBucket: 'vocabulary-28d9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD15A5hcPAJRn7p8Nb6-jwm2VRQnLqaVh0',
    appId: '1:724369051483:ios:21377049cc20307ce0d47e',
    messagingSenderId: '724369051483',
    projectId: 'vocabulary-28d9e',
    storageBucket: 'vocabulary-28d9e.appspot.com',
    iosClientId:
        '724369051483-t53rpcqhvq71d6pbpv2097t0mo8f1448.apps.googleusercontent.com',
    iosBundleId: 'de.vocabulary.vocabulary',
  );
}
